global:
  scrape_interval: 5s
  evaluation_interval: 15s

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9270' ]

  - job_name: 'application'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
