openapi: "3.0.3"
info:
  version: 1.0.0
  title: testService
  description: testService
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: testService
    description: testService
paths:
  /one:
    $ref: "api/apiOne.yaml"
  /two:
    $ref: "api/apiTwo.yaml"
  /three:
    $ref: "api/apiThree.yaml"
  /four/{id}/{uuid}:
    $ref: "api/apiFour.yaml"